name: Build and publish PHP Docker image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      note:
        description: 'Additional note (display on action summary)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/php

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=8.2-ci

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./php/8.2/ci
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update action summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          if [[ "${{ inputs.note }}" != "" ]]; then
            echo "> Note: ${{ inputs.note }}" >> $GITHUB_STEP_SUMMARY
          fi
